### ISSUE TITLE
zfactor and next release of tidyr

### ISSUE THREAD

**Issue by lionel-** [f0nzie/zFactor#1]
Hello,

Posting an issue because the automated email failed to send. We are going to release a new version of tidyr in 10 days and I see the following error in the reverse dependencies checks:

```
Error in ncol(sk_df) : could not find function “ncol”
```

This is most likely caused by the new selection rules for `gather()` and other selecting functions. Please check the breaking changes section in the NEWS file for more information about this error: https://github.com/tidyverse/tidyr/blob/master/NEWS.md

Could you please fix the issue and submit a new version to CRAN, ideally before August 11? Thanks!

**Comment by f0nzie** [comment]
This seems to have disappeared with the new releases. I retested many times and I couldn't reproduce.
I am releasing 1.1.7 within a couple of days. You can take a look at the development version now.

**Comment by f0nzie** [comment]
This issue has been fixed. Refer to new version 0.1.7
